# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michael Edelstone
email: michael.edelstone@gmail.com
description: I’m a pretty happy designer focusing on digital products and brands. I like dogs, national parks, and making useful things with talented people.
url: "https://michaeledelstone.com"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      buttons: "yes"
      button-prev-text: "About me"
      button-prev-link: "/about"
      button-next-text: "Recent work"
      button-next-link: "/portfolio"

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
